//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos.Infrastructure
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class equipodEntities : DbContext
    {

        public equipodEntities()
            : base("name=equipodEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            base.OnModelCreating(modelBuilder);

            // Configurar relaciones explícitas (si es necesario)
            modelBuilder.Entity<Usuarios_Actividades>()
                .HasKey(ua => new { ua.id_usuario, ua.id_actividad });

            modelBuilder.Entity<Usuarios_Actividades>()
                .HasRequired(ua => ua.Usuario)
                .WithMany(u => u.Usuarios_Actividades)
                .HasForeignKey(ua => ua.id_usuario)
                .WillCascadeOnDelete(false);

            modelBuilder.Entity<Usuarios_Actividades>()
                .HasRequired(ua => ua.Actividad)
                .WithMany(a => a.Usuarios_Actividades)
                .HasForeignKey(ua => ua.id_actividad)
                .WillCascadeOnDelete(false);
        }
    
        public virtual DbSet<Actividades> Actividades { get; set; }
        public virtual DbSet<Administradores> Administradores { get; set; }
        public virtual DbSet<Clientes> Clientes { get; set; }
        public virtual DbSet<Monitores> Monitores { get; set; }
        public virtual DbSet<Usuarios> Usuarios { get; set; }

        public DbSet<Usuarios_Actividades> Usuarios_Actividades { get; set; }
        public virtual DbSet<Valoraciones> Valoraciones { get; set; }
    }
}
