//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class users
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public users()
        {
            this.activities = new HashSet<activities>();
            this.activities1 = new HashSet<activities>();
        }
    
        public string dni { get; set; }
        public string names { get; set; }
        public string lastname { get; set; }
        public Nullable<int> phoneN { get; set; }
        public string addres { get; set; }
        public string ccc { get; set; }
        public string pass { get; set; }
        public string user_type { get; set; }
    
        public virtual administradores administradores { get; set; }
        public virtual clientes clientes { get; set; }
        public virtual monitores monitores { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<activities> activities { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<activities> activities1 { get; set; }
    }
}
